name: Run Python Script

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Instalar modelo de traducción
        run: python utils/instalar_paquetes.py

      - name: Ejecutar script
        run: python main.py

      - name: Commit imagen generada
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add images/output/imagen_final.jpg
          git add save/estado.json
          git commit -m "Actualizar imagen del versiculo" || echo "No hay cambios"
          git push
